"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimpleMethodsWithoutDataClumps = exports.InnerInterfaceNegative = exports.MultipleClassesInOneFile = exports.SimpleFields = void 0;
const SimpleFields_1 = require("./simpleFields/SimpleFields");
Object.defineProperty(exports, "SimpleFields", { enumerable: true, get: function () { return SimpleFields_1.SimpleFields; } });
const MultipleClassesInOneFile_1 = require("./simpleFields/MultipleClassesInOneFile");
Object.defineProperty(exports, "MultipleClassesInOneFile", { enumerable: true, get: function () { return MultipleClassesInOneFile_1.MultipleClassesInOneFile; } });
const InnerInterfaceNegative_1 = require("./innerInterfaceNegative/InnerInterfaceNegative");
Object.defineProperty(exports, "InnerInterfaceNegative", { enumerable: true, get: function () { return InnerInterfaceNegative_1.InnerInterfaceNegative; } });
const SimpleMethodsWithoutDataClumps_1 = require("./simpleMethods/SimpleMethodsWithoutDataClumps");
Object.defineProperty(exports, "SimpleMethodsWithoutDataClumps", { enumerable: true, get: function () { return SimpleMethodsWithoutDataClumps_1.SimpleMethodsWithoutDataClumps; } });
