"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RESTAURANTCHANGESUGGESTIONTYPEENUM = exports.APPFEEDBACKTYPEENUM = void 0;
// App-Feedback
var APPFEEDBACKTYPEENUM;
(function (APPFEEDBACKTYPEENUM) {
    APPFEEDBACKTYPEENUM["RESTAURANTEDIT"] = "RESTAURANTEDIT";
    APPFEEDBACKTYPEENUM["APPFEEDBACK"] = "APPFEEDBACK";
})(APPFEEDBACKTYPEENUM = exports.APPFEEDBACKTYPEENUM || (exports.APPFEEDBACKTYPEENUM = {}));
// Restaurant Changes
var RESTAURANTCHANGESUGGESTIONTYPEENUM;
(function (RESTAURANTCHANGESUGGESTIONTYPEENUM) {
    RESTAURANTCHANGESUGGESTIONTYPEENUM["KONTAKT"] = "Kontakt";
    RESTAURANTCHANGESUGGESTIONTYPEENUM["HALALSTATE"] = "Halal Status";
    RESTAURANTCHANGESUGGESTIONTYPEENUM["KATEGORIEN"] = "Kategorien";
    RESTAURANTCHANGESUGGESTIONTYPEENUM["DETAILS"] = "Details";
})(RESTAURANTCHANGESUGGESTIONTYPEENUM = exports.RESTAURANTCHANGESUGGESTIONTYPEENUM || (exports.RESTAURANTCHANGESUGGESTIONTYPEENUM = {}));
//# sourceMappingURL=types.js.map