export const __esModule: boolean;
export const ATN: any;
export const ATNDeserializer: any;
export const BailErrorStrategy: any;
export const CharStream: any;
export const CommonToken: any;
export const CommonTokenStream: any;
export const DFA: any;
export const DiagnosticErrorListener: any;
export const ErrorListener: any;
export const FailedPredicateException: any;
export const InputStream: any;
export const Interval: any;
export const IntervalSet: any;
export const LL1Analyzer: any;
export const Lexer: any;
export const LexerATNSimulator: any;
export const NoViableAltException: any;
export const ParseTreeListener: any;
export const ParseTreeVisitor: any;
export const ParseTreeWalker: any;
export const Parser: any;
export const ParserATNSimulator: any;
export const ParserRuleContext: any;
export const PredictionContextCache: any;
export const PredictionMode: any;
export const RecognitionException: any;
export const RuleContext: any;
export const RuleNode: any;
export const TerminalNode: any;
export const Token: any;
export const arrayToString: any;
export default _default;
declare namespace _default {
    const atn: any;
    const dfa: any;
    const context: any;
    const misc: any;
    const tree: any;
    const error: any;
    const Token: any;
    const CommonToken: any;
    const CharStream: any;
    const InputStream: any;
    const CommonTokenStream: any;
    const Lexer: any;
    const Parser: any;
    const ParserRuleContext: any;
    const Interval: any;
    const IntervalSet: any;
    const LL1Analyzer: any;
    const Utils: any;
}
