export enum RESTAURANTCATEGORYENUM {
  VEGAN = "Vegan",
  VEGETARISCH = "Vegetarisch",
  BURGER = "Burger",
  PIZZA = "Pizza",
  POMMES = "Pommes",
  SUESSES = "Süßes",
  CAFE = "Cafe",
  FRUSHTUCK = "Frühstück",
  KEBAP = "Kebap",
  BACKWAREN = "Backwaren",
  NUDELN = "Nudeln",
  SUPPE = "Suppe",
  EIS = "Eis",
  SUSHI = "Sushi",
  WRAPS = "Wraps",
  FINGERFOOD = "Fingerfood",
  STEAKS = "Steaks",
  FISCH = "Fisch",
  KUCHEN = "Kuchen",
  SALATE = "Salate",
  FALAFEL = "Falafel",
  CIGKOFTE = "Cig Köfte",
  TUERKISCH = "Türkisch",
  ITALIENISCH = "Italienisch",
  ARABISCH = "Arabisch",
  ASIATISCH = "Asiatisch",
  INDISCH = "Indisch",
  SONSTIGES = "Sonstiges",
}

export enum RESTAURANTDETAILSEMUM {
  GEBET = "Gebetsmöglichkeit",
  SITZ = "Sitzmöglichkeit",
  PARK = "Parkmöglichkeit",
  KARTE = "Kartenzahlung",
  WC = "WC",
  WLAN = "WLAN",
  IMFREIEN = "Plätze im Freien",
  LIEFERUNG = "Lieferdienst",
  RESERVIERUNG = "Reservierung möglich",
  BARRIEREFREI = "Barrierefrei",
}
